defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: dql_d4rl
mode: training  # training -> inference
seed: 0
device_id: 0

# Actor
solver: ddpm
sampling_steps: 5

# Training
training_steps: 10000
ema_update_interval: 5
log_interval: 1000
save_interval: 10000

# Inference
ckpt: 10000
num_envs: 50
num_episodes: 1
num_candidates: 50
temperature: 1.0
use_ema: True

# hydra
hydra:
  job:
    chdir: false

