defaults:
  - _self_
  - task: kitchen-mixed-v0

pipeline_name: adaptdiffuser_d4rl_kitchen
mode: inference
seed: 0
device: cuda:0

# Environment
discount: 0.997

# Diffuser
solver: ddpm
model_dim: 64
diffusion_steps: 20
sampling_steps: 20
predict_noise: False
action_loss_weight: 10.
ema_rate: 0.9999

# Training
diffusion_gradient_steps: 1000000
classifier_gradient_steps: 1000000
batch_size: 64
log_interval: 1000
save_interval: 100000

# Inference
ft_ckpt: latest
ckpt: latest
num_envs: 50
num_episodes: 3
num_candidates: 64
temperature: 0.5
use_ema: True

# hydra
hydra:
  job:
    chdir: false

