defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: idql_d4rl
device_id: 0
mode: bc_training  # bc_training -> iql_training (optional) -> inference
seed: 0

# Environment
normalize_reward: True

# Training
bc_training_steps: 10000
iql_training_steps: 10000
save_interval: 10000

# Inference
bc_ckpt: 10000
iql_ckpt: 10000
solver: ddpm
iql_from_pretrain: True
sampling_steps: 5
num_envs: 50
num_episodes: 1
num_candidates: 256

# hydra
hydra:
  job:
    chdir: false
