defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: idql_d4rl
device_id: 0
mode: bc_training
seed: 0

# Environment
normalize_reward: True

# Actor
solver: ddpm
diffusion_steps: 5
sampling_steps: 5

# Critic
critic_hidden_dim: 256
critic_learning_rate: 0.0003

# Training
bc_training_steps: 1000000
iql_training_steps: 1000000
batch_size: 256
save_interval: 100000

# Inference
ckpt: latest
num_envs: 50
num_episodes: 3
num_candidates: 256
temperature: 0.5
use_ema: True

# hydra
hydra:
  job:
    chdir: false

