defaults:
  - _self_
  - task: antmaze-medium-play-v2

pipeline_name: dd_d4rl_antmaze
mode: train
seed: 0
device: cuda:0

# Environment
noreaching_penalty: -100
discount: 0.99

# DD
solver: ddim
## Network Architecture
emb_dim: 128
d_model: 320
n_heads: 10
depth: 2
label_dropout: 0.25
sampling_steps: 20
predict_noise: True
next_obs_loss_weight: 10.
ema_rate: 0.9999

# Training
diffusion_gradient_steps: 1000000
invdyn_gradient_steps: 200000
batch_size: 64
log_interval: 1000
save_interval: 100000

# Inference
diffusion_ckpt: latest
invdyn_ckpt: latest
num_envs: 50
num_episodes: 3
temperature: 0.5
use_ema: True

# hydra
hydra:
  job:
    chdir: false

