defaults:
  - _self_
  - task: halfcheetah-medium-expert-v2

pipeline_name: diffuser_d4rl
device_id: 0
mode: training  # training -> inference
seed: 0

# Training
diffusion_training_steps: 10000
classifier_training_steps: 10000
save_interval: 10000

# Inference
ckpt: 10000
solver: ddpm
sampling_steps: 5
num_envs: 50
num_episodes: 1
num_candidates: 64

# hydra
hydra:
  job:
    chdir: false
